os: linux
dist: focal
language: node_js
node_js:
  - 15

before_install:
  - cd UD-Viz-Core
  - npm install -g npm@6.14.10
  - npm --version

install:
  - npm install

jobs:
  include:
    - stage: lint
      script:
        - ./node_modules/eslint/bin/eslint.js --version
        - npm run lint
